sonar.projectKey=mlaurajeronimo_provaTeste-e2e
sonar.organization=mlaurajeronimo
sonar.projectName=provaTeste-e2e
sonar.projectVersion=1.0
sonar.sources=src/support
sonar.tests=src/scenarios
sonar.exclusions=artifacts/**,test-results/**,playwright-report/**,node_modules/**
sonar.sourceEncoding=UTF-8
